import challenges1 from "../../images/retos.jpeg";

export const challengesData = [
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
        url: "https://github.com/yicell52",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
    {
        img: challenges1,
        alt: "challenges",
        name: "",
        button: "Ir al reto",
    },
];
